# Generated by Django 4.1.4 on 2023-09-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
