# Generated by Django 4.1.4 on 2023-09-04 03:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('numeric', 'numeric'), ('time', 'time'), ('boolean', 'boolean')], max_length=255)),
                ('units', models.CharField(blank=True, max_length=255)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(blank=True)),
                ('numerical', models.IntegerField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracking.habit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='habit_date_unique'),
        ),
    ]
