# Generated by Django 4.1.4 on 2023-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='numeric_goal',
            field=models.IntegerField(null=True),
        ),
    ]
