# Generated by Django 4.1.4 on 2023-09-04 03:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_habit_numeric_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, size=None),
        ),
    ]
