# Generated by Django 4.1.4 on 2023-09-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_habitentry_habit_date_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
