# Generated by Django 4.1.4 on 2023-09-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_habit_numeric_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='numerical',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
