# Generated by Django 4.1.4 on 2023-09-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_habitentry_numerical'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
