# Generated by Django 4.1.4 on 2023-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_habit_is_archived'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitentry',
            name='habit_date_unique',
        ),
        migrations.AddConstraint(
            model_name='habitentry',
            constraint=models.UniqueConstraint(models.F('habit_id'), models.F('date'), name='habit_date_unique'),
        ),
    ]
