# Generated by Django 4.1.4 on 2023-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_remove_habitentry_habit_date_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user_id', 'is_public'], name='tracking_ha_user_id_6b82c7_idx'),
        ),
    ]
