# Generated by Django 4.1.4 on 2023-09-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_habit_is_public_habit_tracking_ha_user_id_6b82c7_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='habit',
            new_name='user_public_habit_idx',
            old_name='tracking_ha_user_id_6b82c7_idx',
        ),
    ]
